name: Send Random Picture to Discord

on:
  schedule:
    - cron: "0 7 * * *"
  workflow_dispatch:

jobs:
  send_pic:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      
      - name: Install requests
        run: pip install requests
      
      - name: Send random image to Discord
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: python send_random_pic.py
